CXX = g++
CXXFLAGS = -std=c++0x
CXXFLAGS += -Wall
CXXFLAGS += -pedantic-errors
CXXFLAGS += -g

SRCS = main.cpp menu.hpp menu.cpp Character.cpp Character.hpp Barbarian.cpp Barbarian.hpp BlueMen.cpp BlueMen.hpp HarryPotter.cpp HarryPotter.hpp Medusa.cpp Medusa.hpp Vampire.cpp Vampire.hpp

vector: ${SRC}
	${CXX} ${CXXFLAGS} ${SRCS} -o proj3