CXX = g++
CXXFLAGS = -std=c++0x
CXXFLAGS += -Wall
CXXFLAGS += -pedantic-errors
CXXFLAGS += -g

SRCS = main.cpp Space.cpp Space.hpp corridor.cpp corridor.hpp doorRoom.cpp doorRoom.hpp entrance.cpp entrance.hpp problemRoom.cpp problemRoom.hpp endingroom.cpp endingroom.hpp

vector: ${SRC}
	${CXX} ${CXXFLAGS} ${SRCS} -o final