CXX = g++
CXXFLAGS = -std=c++0x
CXXFLAGS += -Wall
CXXFLAGS += -pedantic-errors
CXXFLAGS += -g

SRCS = Crittermain.cpp Ant.cpp Ant.hpp Doodlebug.cpp Doodlebug.hpp Critter.hpp Critter.cpp

vector: ${SRC}
	${CXX} ${CXXFLAGS} ${SRCS} -o group14